# Project-wide Gradle settings.

# JVM Arguments: 4GB of heap and UTF-8 encoding.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

# Optimization settings (Not enabled by default)
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mandatory for projects using AndroidX libraries
android.useAndroidX=true
android.enableJetifier=false

# Use official Kotlin code style.
kotlin.code.style=official
android.uniquePackageNames=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false

# Suppress warnings about iOS tasks on non-macOS hosts
kotlin.native.ignoreDisabledTargets=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
