@startuml
!define COMPONENT(name) component name
!define FRAGMENT(name) component name <<Fragment>>

package "profile" {
    FRAGMENT(ProfileFragment)
    FRAGMENT(FightersPageFragment)
    FRAGMENT(DecksPageFragment)
    FRAGMENT(ProfileBottomSheet)
    COMPONENT(FightersViewModel)
    COMPONENT(DecksViewModel)

    package "record" {
        FRAGMENT(RecordFighterDialogFragment)
        FRAGMENT(RecordDeckDialogFragment)
        FRAGMENT(DeleteFighterDialogFragment)
        FRAGMENT(DeleteDeckDialogFragment)
    }
}

package "Data Layer" {
    COMPONENT(FightersRepository)
}

' --- Dependencies ---

ProfileFragment ..> FightersViewModel
ProfileFragment ..> DecksViewModel
ProfileFragment -> FightersPageFragment : "shows in ViewPager"
ProfileFragment -> DecksPageFragment : "shows in ViewPager"

FightersPageFragment ..> FightersViewModel
DecksPageFragment ..> FightersViewModel
DecksPageFragment ..> DecksViewModel

FightersPageFragment ..> ProfileBottomSheet : "shows"
FightersPageFragment ..> RecordFighterDialogFragment : "shows"
FightersPageFragment ..> DeleteFighterDialogFragment : "shows"
DecksPageFragment ..> ProfileBottomSheet : "shows"
DecksPageFragment ..> RecordDeckDialogFragment : "shows"
DecksPageFragment ..> DeleteDeckDialogFragment : "shows"

RecordFighterDialogFragment ..> FightersViewModel
RecordDeckDialogFragment ..> DecksViewModel
DeleteFighterDialogFragment ..> FightersViewModel
DeleteDeckDialogFragment ..> DecksViewModel

FightersViewModel -> FightersRepository
DecksViewModel -> FightersRepository
@enduml
