@startuml
!define COMPONENT(name) component name
!define FRAGMENT(name) component name <<Fragment>>

package "profile" {
    FRAGMENT(ProfileFragment)
    FRAGMENT(FightersPageFragment)
    FRAGMENT(CollectionsPageFragment)
    COMPONENT(ProfileViewModel)
    COMPONENT(FightersViewModel)
    COMPONENT(CollectionsViewModel)
}

package "Data Layer" {
    COMPONENT(FightersRepository)
}

' --- Dependencies ---

ProfileFragment ..> ProfileViewModel
ProfileFragment -> FightersPageFragment : "shows in ViewPager"
ProfileFragment -> CollectionsPageFragment : "shows in ViewPager"

FightersPageFragment ..> ProfileViewModel
FightersPageFragment ..> FightersViewModel
CollectionsPageFragment ..> ProfileViewModel
CollectionsPageFragment ..> CollectionsViewModel

FightersViewModel -> FightersRepository
CollectionsViewModel -> FightersRepository

@enduml
