@startuml
title Module Dependency Diagram

!define App(name, desc) package "desc" as name <<Android App>>
!define Lib(name, desc) package "desc" as name <<Android Library>>

App(android, ":android")
Lib(database, ":database")
Lib(shared, ":shared")

android --> database
database --> shared

@enduml
