/*
 * Copyright (c) 2026 Ryuusuke Azuma All Rights Reserved.
 */

@startuml
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define primary_key(x) <b>PK: x</b>
!define foreign_key(x) <i>FK: x</i>

hide methods
hide stereotypes

skinparam class {
    BackgroundColor white
    ArrowColor #263238
    BorderColor #263238
}

Table(game, "game (対戦概要)") {
    primary_key(id) INTEGER
    game_name TEXT NOT NULL
    game_date INTEGER NOT NULL
    game_style INTEGER NOT NULL
    memo TEXT NOT NULL
}

Table(score, "score (対戦結果)") {
    primary_key(id) INTEGER
    foreign_key(game_id) INTEGER
    battle_deck TEXT NOT NULL
    matching_deck TEXT NOT NULL
    win_lose INTEGER NOT NULL
    team_result INTEGER
    team_win_lose INTEGER
    memo TEXT NOT NULL
}

game "1" -- "0..*" score : "game_id"
@enduml
